name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --prod --yes \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --env SUPABASE_URL=https://eflzhvxrymhfvyfbxkrw.supabase.co \
            --env SUPABASE_STORAGE_URL=https://eflzhvxrymhfvyfbxkrw.supabase.co/storage/v1/object/public \
            --env SUPABASE_BUCKET_NAME=audios \
            --env SUPABASE_FOLDER=lynne_hospital
